### ISSUE TITLE
Cask issues

### ISSUE THREAD

**Issue by syoung-quizlet** [Honestpuck/homebrew.sh#1]
Thank you for writing this.  This has been our primary hurdle with deploying zero touch MacOS.

I noticed after running it that I could not install applications using cask.  I noticed the /usr/local/Caskroom directory did not exist.  I created it and set the appropriate permissions and then was able to run brew cask install.

```
mkdir /usr/local/Caskroom
sudo chown -R $consoleuser /usr/local/Caskroom
```
Not sure if this is specific to me or if it may be an issue others may have.

Reference: https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/permission_denied_error.md

**Comment by Honestpuck** [comment]
Finally got around to testing adding in the `mkdir /usr/local/Caskroom` so closing this. Thanks for the suggestion.
