### ISSUE TITLE
Installing your script in Addigy MDM

### ISSUE THREAD

**Issue by erickgrau** [Honestpuck/homebrew.sh#3]
I tried to run this as a script in Addigy (similar to JAMF) and I get this error:
Error: /usr/local is not writable. You should change the
ownership and permissions of /usr/local back to your
user account:
  sudo chown -R $(whoami) /usr/local

Help please! :)

**Comment by Honestpuck** [comment]
I suspect that Addigy is running the scripts at a user level, rather than with admin privileges, which is what Jamf does.

Does Addigy have some sort of setting to control this? I don't have enough experience with Addigy to know.

**Comment by Honestpuck** [comment]
I'm closing this as I don't claim to support Addigy and don't have anything to test on.
